# Generated by Django 4.2.11 on 2024-03-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('post_description', models.CharField(default='', max_length=500)),
                ('post_type', models.CharField(choices=[('0', 'CLIENT'), ('1', 'FREELANCER')], max_length=50)),
                ('post_state', models.CharField(choices=[('0', 'IN PROGRESS'), ('1', 'RESOLVED')], max_length=50)),
                ('suspicious_post_state', models.CharField(choices=[('0', 'NOT SUSPECTED'), ('1', 'SUSPECTED')], max_length=50)),
                ('in_channel', models.BooleanField(default=False)),
                ('massage_id_in_channel', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('chat_id', models.CharField(default='', max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(blank=True, related_name='user_post', to='ProjectsCollab.post')),
                ('user_comments_and_suggestions', models.ManyToManyField(blank=True, related_name='user_comments_feedback', to='ProjectsCollab.user_feedback')),
                ('user_reports', models.ManyToManyField(blank=True, related_name='user_report_feedback', to='ProjectsCollab.user_feedback')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectsCollab.user'),
        ),
    ]
