# Generated by Django 4.0.6 on 2024-03-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0002_post_post_floor_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(default='', max_length=100)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_recipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_receipt', to='ProjectsCollab.transaction_receipt'),
        ),
    ]
