# Generated by Django 4.0.6 on 2024-03-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0004_transaction_receipt_payment_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_recipt',
            new_name='post_receipt',
        ),
    ]
