# Generated by Django 4.2.11 on 2024-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0006_alter_post_post_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_receipt',
            name='transaction_post_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
