# Generated by Django 4.2.11 on 2024-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0009_user_user_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_receipt',
        ),
        migrations.AddField(
            model_name='user',
            name='user_receipts',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_receipt', to='ProjectsCollab.transaction_receipt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='massage_id_in_channel',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_comments_and_suggestions',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_comments_feedback', to='ProjectsCollab.user_feedback'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_report_feedback', to='ProjectsCollab.user_feedback'),
        ),
    ]
