# Generated by Django 4.2.11 on 2024-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0010_remove_post_post_receipt_user_user_receipts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_comments_and_suggestions',
            field=models.ManyToManyField(blank=True, related_name='user_comments_feedback', to='ProjectsCollab.user_feedback'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_receipts',
            field=models.ManyToManyField(blank=True, related_name='post_receipt', to='ProjectsCollab.transaction_receipt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_reports',
            field=models.ManyToManyField(blank=True, related_name='user_report_feedback', to='ProjectsCollab.user_feedback'),
        ),
    ]
