# Generated by Django 4.2.11 on 2024-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0012_remove_transaction_receipt_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_credit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
