# Generated by Django 4.2.11 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0013_alter_user_user_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_receipt',
            old_name='transaction_contract_hash',
            new_name='transaction_contract_address',
        ),
        migrations.AddField(
            model_name='transaction_receipt',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
