# Generated by Django 4.2.11 on 2024-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0015_transaction_receipt_transaction_blocktimestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_receipt',
            old_name='transaction_contract_address',
            new_name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='transaction_receipt',
            name='transaction_blocktimestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='feedback_content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
