# Generated by Django 4.2.11 on 2024-04-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0016_rename_transaction_contract_address_transaction_receipt_transaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectsCollab.user')),
            ],
        ),
    ]
