# Generated by Django 4.2.11 on 2024-04-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsCollab', '0017_user_user_is_blocked_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
